"""
run_shap: Compute SHAP values for model predictions per time window.
generate_shap_summary: Generate a textual summary or JSON report from SHAP analysis results.
"""

import shap
import pandas as pd
from typing import Dict, List, Set, Tuple

def run_shap(model, window_df: pd.DataFrame) -> Dict[str, List[float]]:
    # normalize column names
    window_df.columns = [col.strip().lower() for col in window_df.columns]

    # drop columns that are not features for predicting PM10
    x_shap = window_df.drop(columns=[   "stazione",
                                        "data",
                                        "inquinante",
                                        "unità di misura",
                                        "latitudine",
                                        "longitudine",
                                        "valore",
                                        "nazione",
                                        "comune",
                                        "stazionemeteo",
                                        "lombardia_ma_0_min_lat",
                                        "lombardia_ma_0_min_lon",
                                        "lombardia_ma_0_max_lat",
                                        "lombardia_ma_0_max_lon",
                                        "lombardia_ma_0_unità di misura",
                                        "lombardia_ma_1_min_lon",
                                        "lombardia_ma_1_min_lat",
                                        "lombardia_ma_1_max_lat",
                                        "lombardia_ma_1_max_lon",
                                        "lombardia_ma_1_unità di misura",
                                        "lombardia_ma_2_min_lon",
                                        "lombardia_ma_2_min_lat",
                                        "lombardia_ma_2_max_lat",
                                        "lombardia_ma_2_max_lon",
                                        "lombardia_ma_2_unità di misura",
                                        "lombardia_ma_3_min_lon",
                                        "lombardia_ma_3_min_lat",
                                        "lombardia_ma_3_max_lat",
                                        "lombardia_ma_3_max_lon",
                                        "lombardia_ma_3_unità di misura",
                                        "lombardia_ma_4_min_lon",
                                        "lombardia_ma_4_min_lat",
                                        "lombardia_ma_4_max_lat",
                                        "lombardia_ma_4_max_lon",
                                        "lombardia_ma_4_unità di misura",
                                        "lombardia_ma_5_min_lon",
                                        "lombardia_ma_5_min_lat",
                                        "lombardia_ma_5_max_lat",
                                        "lombardia_ma_5_max_lon",
                                        "lombardia_ma_5_unità di misura",
                                        "lombardia_ma_6_min_lon",
                                        "lombardia_ma_6_min_lat",
                                        "lombardia_ma_6_max_lat",
                                        "lombardia_ma_6_max_lon",
                                        "lombardia_ma_6_unità di misura",
                                        "lombardia_ma_7_min_lon",
                                        "lombardia_ma_7_min_lat",
                                        "lombardia_ma_7_max_lat",
                                        "lombardia_ma_7_max_lon",
                                        "lombardia_ma_7_unità di misura",
                                        "lombardia_ma_8_min_lon",
                                        "lombardia_ma_8_min_lat",
                                        "lombardia_ma_8_max_lat",
                                        "lombardia_ma_8_max_lon",
                                        "lombardia_ma_8_unità di misura",
                                        "lombardia_ma_9_min_lon",
                                        "lombardia_ma_9_min_lat",
                                        "lombardia_ma_9_max_lat",
                                        "lombardia_ma_9_max_lon",
                                        "lombardia_ma_9_unità di misura",
                                        "lombardia_ma_10_min_lon",
                                        "lombardia_ma_10_min_lat",
                                        "lombardia_ma_10_max_lat",
                                        "lombardia_ma_10_max_lon",
                                        "lombardia_ma_10_unità di misura",
                                        "lombardia_ma_11_min_lon",
                                        "lombardia_ma_11_min_lat",
                                        "lombardia_ma_11_max_lat",
                                        "lombardia_ma_11_max_lon",
                                        "lombardia_ma_11_unità di misura",
                                        "lombardia_ma_12_min_lon",
                                        "lombardia_ma_12_min_lat",
                                        "lombardia_ma_12_max_lat",
                                        "lombardia_ma_12_max_lon",
                                        "lombardia_ma_12_unità di misura",
                                        "lombardia_ma_13_min_lon",
                                        "lombardia_ma_13_min_lat",
                                        "lombardia_ma_13_max_lat",
                                        "lombardia_ma_13_max_lon",
                                        "lombardia_ma_13_unità di misura",
                                        "lombardia_ma_14_min_lon",
                                        "lombardia_ma_14_min_lat",
                                        "lombardia_ma_14_max_lat",
                                        "lombardia_ma_14_max_lon",
                                        "lombardia_ma_14_unità di misura",
                                        "lombardia_ma_15_min_lon",
                                        "lombardia_ma_15_min_lat",
                                        "lombardia_ma_15_max_lat",
                                        "lombardia_ma_15_max_lon",
                                        "lombardia_ma_15_unità di misura",
                                        "lombardia_ma_16_min_lon",
                                        "lombardia_ma_16_min_lat",
                                        "lombardia_ma_16_max_lat",
                                        "lombardia_ma_16_max_lon",
                                        "lombardia_ma_16_unità di misura",
                                        "lombardia_ma_17_min_lon",
                                        "lombardia_ma_17_min_lat",
                                        "lombardia_ma_17_max_lat",
                                        "lombardia_ma_17_max_lon",
                                        "lombardia_ma_17_unità di misura",
                                        "veneto_ma_0_min_lon",
                                        "veneto_ma_0_min_lat",
                                        "veneto_ma_0_max_lat",
                                        "veneto_ma_0_max_lon",
                                        "veneto_ma_0_unità di misura",
                                        "veneto_ma_1_min_lon",
                                        "veneto_ma_1_min_lat",
                                        "veneto_ma_1_max_lat",
                                        "veneto_ma_1_max_lon",
                                        "veneto_ma_1_unità di misura",
                                        "veneto_ma_2_min_lon",
                                        "veneto_ma_2_min_lat",
                                        "veneto_ma_2_max_lat",
                                        "veneto_ma_2_max_lon",
                                        "veneto_ma_2_unità di misura",
                                        "veneto_ma_6_min_lon",
                                        "veneto_ma_6_min_lat",
                                        "veneto_ma_6_max_lat",
                                        "veneto_ma_6_max_lon",
                                        "veneto_ma_6_unità di misura",
                                        "veneto_ma_7_min_lon",
                                        "veneto_ma_7_min_lat",
                                        "veneto_ma_7_max_lat",
                                        "veneto_ma_7_max_lon",
                                        "veneto_ma_7_unità di misura",
                                        "veneto_ma_8_min_lon",
                                        "veneto_ma_8_min_lat",
                                        "veneto_ma_8_max_lat",
                                        "veneto_ma_8_max_lon",
                                        "veneto_ma_8_unità di misura",
                                        "veneto_ma_9_min_lon",
                                        "veneto_ma_9_min_lat",
                                        "veneto_ma_9_max_lat",
                                        "veneto_ma_9_max_lon",
                                        "veneto_ma_9_unità di misura",
                                        "veneto_ma_11_min_lon",
                                        "veneto_ma_11_min_lat",
                                        "veneto_ma_11_max_lat",
                                        "veneto_ma_11_max_lon",
                                        "veneto_ma_11_unità di misura",
                                        "veneto_ma_12_min_lon",
                                        "veneto_ma_12_min_lat",
                                        "veneto_ma_12_max_lat",
                                        "veneto_ma_12_max_lon",
                                        "veneto_ma_12_unità di misura",
                                        "veneto_ma_13_min_lon",
                                        "veneto_ma_13_min_lat",
                                        "veneto_ma_13_max_lat",
                                        "veneto_ma_13_max_lon",
                                        "veneto_ma_13_unità di misura",
                                        "veneto_ma_14_min_lon",
                                        "veneto_ma_14_min_lat",
                                        "veneto_ma_14_max_lat",
                                        "veneto_ma_14_max_lon",
                                        "veneto_ma_14_unità di misura",
                                        "veneto_ma_15_min_lon",
                                        "veneto_ma_15_min_lat",
                                        "veneto_ma_15_max_lat",
                                        "veneto_ma_15_max_lon",
                                        "veneto_ma_15_unità di misura",
                                        "veneto_ma_16_min_lon",
                                        "veneto_ma_16_min_lat",
                                        "veneto_ma_16_max_lat",
                                        "veneto_ma_16_max_lon",
                                        "veneto_ma_16_unità di misura",
                                        "veneto_ma_17_min_lon",
                                        "veneto_ma_17_min_lat",
                                        "veneto_ma_17_max_lat",
                                        "veneto_ma_17_max_lon",
                                        "veneto_ma_17_unità di misura",
                                        "veneto_ma_18_min_lon",
                                        "veneto_ma_18_min_lat",
                                        "veneto_ma_18_max_lat",
                                        "veneto_ma_18_max_lon",
                                        "veneto_ma_18_unità di misura"])

    explainer: shap.Explainer = shap.Explainer(model, x_shap)
    shap_values: shap.Explanation = explainer(x_shap)
    shap_df: pd.DataFrame = pd.DataFrame(shap_values.values, columns=x_shap.columns)
    mean_abs: pd.Series = shap_df.abs().mean().sort_values(ascending=False)
    return {
        "mean_shap": mean_abs,
        "top_features": mean_abs.head(10).to_dict()
    }

def generate_shap_summary(shap_result, window_index):
    text = f"""
    SHAP Summary for Window {window_index}:
    Top Influential Features:
    {shap_result['top_features']}
    """
    return text.strip()